ops:
  score_members_aca:
    config:
      claims_view: main_raw.raw_claims_2023
      enrollments_view: main_raw.raw_enrollments_2023
      members_view: main_raw.raw_members_2023
      invalid_gender: skip
      diy_model_year: "2023"
      member_age_basis_year: "2023"
      run_description: "ACA scoring run 2023"

resources:
  duckdb:
    config:
      path: /home/garth/garage/prism/risk_adjustment.duckdb
