ops:
  score_members_aca:
    config:
      claims_view: main_raw.claims_2022_3months
      enrollments_view: main_raw.raw_enrollments_2022
      members_view: main_raw.raw_members_2022
      invalid_gender: skip
      diy_model_year: "2022"
      member_age_basis_year: "2022"
      run_description: "Lag Analysis 2022 (3-month runout)"

resources:
  duckdb:
    config:
      path: /home/garth/garage/prism/risk_adjustment.duckdb
