ops:
  compare_runs:
    config:
      run_id_a: "5b7e3047-0779-4281-a1d5-fe18b5c54d2a"
      run_id_b: "c60e4ede-c9b4-4a02-9d32-2790b39d6c95"
      run_description: "Audit Risk / Truncation Analysis"
      metric: "mean"
      population_mode: "intersection"

resources:
  duckdb:
    config:
      path: /home/garth/garage/prism/risk_adjustment.duckdb
