ops:
  compare_runs:
    config:
      run_id_a: "5b7e3047-0779-4281-a1d5-fe18b5c54d2a"
      run_id_b: "65029b02-929a-4872-839e-647c68ef8735"
      run_description: "Benefit Design (Metal Level) Impact Analysis"
      metric: "mean"
      population_mode: "intersection"

resources:
  duckdb:
    config:
      path: /home/garth/garage/prism/risk_adjustment.duckdb
